
version: '3.8'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: litestar_app
    env_file:
      - .env
    environment:
      DB_HOST: db
    ports:
      - "8080:8000"
    depends_on:
      db:
        condition: service_healthy 
    volumes:
      - ./src:/app/src
    networks:
      - app_network

  db:
    image: postgres:16-alpine
    container_name: postgres_db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5400:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s # Даем время на запуск перед первыми проверками
    networks:
      - app_network
volumes:
  postgres_data:
    driver: local
networks:
  app_network:
    driver: bridge
